version: '3.8'

services:
  jenkins:
    build: .
    image: myjenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home_2:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - selenoid_net
    restart: unless-stopped

volumes:
  jenkins_home_2:

networks:
  selenoid_net:
    external: true