version: '3.8'

services:

  phpadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=bn_opencart
    ports:
      - '8889:80'
    networks:
      - selenoid_net

  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    ports:
      - '3306:3306'
    networks:
      - selenoid_net

  opencart:
    image: agridyaev/opencart:4.0.2-3-debian-12-r33
    ports:
      - '8081:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=172.20.150.187:8081
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - mariadb
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - selenoid_net

  tests:
    build: ../..
    image: opencart-tests
    depends_on:
      opencart:
        condition: service_healthy
    command: [
      "pytest",
      "tests/",
      "--url", "http://opencart:8080/",
      "--remote",
      "--remote_url", "http://ggr:4444/wd/hub",
      "--browser", "chrome",
      "--browser_version", "128.0",
      "--db_host", "mariadb",
      "--db_user", "bn_opencart",
      "--db_name", "bitnami_opencart"
    ]
    networks:
      - selenoid_net

networks:
  selenoid_net:
    external: true